### ISSUE TITLE
Can not set up to work in hassio (pi3)

### ISSUE THREAD

**Issue by blazkom** [arthurkrupa/gree-hvac-mqtt-bridge#23]
I am trying to make this script to work on hassio on pi3.
But seams like gree air conditioner and this plugin can not work together :/ 

I get entites climate but when i change any settings gree does not recrive this comand.

This is script that i have instaled on hassio
CONFIG:
`{
  "hvac_host": "192.168.1.111",
  "mqtt": {
    "broker_url": "192.168.1.131:1883",
    "topic_prefix": "home/greehvac",
    "username": "homeassistant",
    "password": "hello"
  }
}`

`climate:
  - platform: mqtt

    # Change to whatever you want
    name: Gree HVAC

    # Change  to what you've set in addon options
    current_temperature_topic: "home/greehvac/temperature/get"
    temperature_command_topic: "home/greehvac/temperature/set"
    temperature_state_topic: "home/greehvac/temperature/get"
    mode_state_topic: "home/greehvac/mode/get"
    mode_command_topic: "home/greehvac/mode/set"
    fan_mode_state_topic: "home/greehvac/fanspeed/get"
    fan_mode_command_topic: "home/greehvac/fanspeed/set"
    swing_mode_state_topic: "home/greehvac/swingvert/get"
    swing_mode_command_topic: "home/greehvac/swingvert/set"
    power_state_topic: "home/greehvac/power/get"
    power_command_topic: "home/greehvac/power/set"

    # Keep the following as is
    payload_off: 0
    payload_on: 1
    modes:
      - "off"
      - "auto"
      - "cool"
      - "heat"
      - "dry"
      - "fan_only"
    swing_modes:
      - "default"
      - "full"
      - "fixedTop"
      - "fixedMidTop"
      - "fixedMid"
      - "fixedMidBottom"
      - "fixedBottom"
      - "swingBottom"
      - "swingMidBottom"
      - "swingMid"
      - "swingMidTop"
      - "swingTop"
    fan_modes:
      - "auto"
      - "low"
      - "mediumLow"
      - "medium"
      - "mediumHigh"
      - "high"
`

**Comment by wjketting** [comment]
check this one [https://github.com/arthurkrupa/gree-hvac-mqtt-bridge/issues/10](url)

did it for me.

**Comment by blazkom** [comment]
I have now check everything.
- I have make mqtt server just for this porpouse, anonymus can connect to it.

I always get this reply in my log

`added 61 packages from 47 contributors and audited 208 packages in 10.537s
found 0 vulnerabilities
events.js:167
      throw er; // Unhandled 'error' event
      ^
Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/usr/src/app/node_modules/mqtt/lib/client.js:871:15)
    at MqttClient._handlePacket (/usr/src/app/node_modules/mqtt/lib/client.js:319:12)
    at work (/usr/src/app/node_modules/mqtt/lib/client.js:261:12)
    at Writable.writable._write (/usr/src/app/node_modules/mqtt/lib/client.js:271:5)
    at doWrite (/usr/src/app/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/usr/src/app/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at Writable.write (/usr/src/app/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Socket.ondata (_stream_readable.js:666:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
Emitted 'error' event at:
    at MqttClient._handleConnack (/usr/src/app/node_modules/mqtt/lib/client.js:873:10)
    at MqttClient._handlePacket (/usr/src/app/node_modules/mqtt/lib/client.js:319:12)
    [... lines matching original stack trace ...]
    at addChunk (_stream_readable.js:283:12)`
