### ISSUE TITLE
SwingHor Issue

### ISSUE THREAD

**Issue by knackrack615** [arthurkrupa/gree-hvac-mqtt-bridge#24]
Just updated to the latest version and it looks like it doesn't like that it can't find swinghor on my model

```added 61 packages from 47 contributors and audited 208 packages in 2.905s
found 0 vulnerabilities
[MQTT] Connected to broker on mqtt://192.168.1.36
[UDP] Connected to device at 192.168.1.13
[UDP] New device registered: Office AC
[UDP] Device Office AC is bound!
/usr/src/app/index.js:33
    client.publish(mqttTopicPrefix + '/swinghor/get', commands.swingHor.value.getKeyByValue(deviceModel.props[commands.swingHor.code]).toString());
                                                                                                                                      ^
TypeError: Cannot read property 'toString' of undefined
    at Object.onStatus (/usr/src/app/index.js:33:135)
    at Device._handleResponse (/usr/src/app/app/deviceFactory.js:174:26)
    at Socket.Device.socket.on (/usr/src/app/app/deviceFactory.js:47:51)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:659:8)```

**Comment by wjketting** [comment]
Seems like same error I had with the quiet mode.
Suggest to follow Arthur's procedure ([https://github.com/arthurkrupa/gree-hvac-mqtt-bridge/issues/21](url)) to find out what swingHor code is causing the issue and put the results here.

**Comment by wjketting** [comment]
...or put your airco in different horizontal swing mode (fixed) and try running the bridge.

**Comment by knackrack615** [comment]
Disabling horizontal swing through the native app seems to fix the issue.

I really wish i could help with debugging this but right now i'm away from home and probably wont be back for at-least a week
