### ISSUE TITLE
New Multiple ACs version, getting error

### ISSUE THREAD

**Issue by dragonflyuk** [arthurkrupa/gree-hvac-mqtt-bridge#37]
I've setup my 4 units, but I'm getting the following errors repeatedly at the moment. I get the feeling I'm missing a config or similiar.

 [UDP] Device 1e4837fc is bound!
0|HVAC_0  | TypeError: Cannot read property 'toString' of undefined
0|HVAC_0  |     at Object.onStatus (/usr/src/app/index.js:57:96)
0|HVAC_0  |     at Device._handleResponse (/usr/src/app/app/deviceFactory.js:171:20)
0|HVAC_0  |     at Socket.Device.socket.on (/usr/src/app/app/deviceFactory.js:45:47)
0|HVAC_0  |     at Socket.emit (events.js:182:13)
0|HVAC_0  |     at UDP.onMessage [as onmessage] (dgram.js:628:8)
0|HVAC_0  | [MQTT] Connecting to mqtt://192.168.1.3 as "local-user"...
0|HVAC_0  | 

Here is my config

`{
  "mqtt": {
    "broker_url": "mqtt://192.168.1.3",
    "username": "local-user",
    "password": "xxxxxxxxxxx"
  },
  "devices": [
    {
      "hvac_host": "192.168.1.157",
      "mqtt_topic_prefix": "home/greehvacbedroomup"
    },
    {
      "hvac_host": "192.168.1.97",
      "mqtt_topic_prefix": "home/greehvac-bedroom-down"
    },
    {
      "hvac_host": "192.168.1.112",
      "mqtt_topic_prefix": "home/greehvac-kitchen"
    },
    {
      "hvac_host": "192.168.1.83",
      "mqtt_topic_prefix": "home/greehvac"
    }
  ]
}`

**Comment by arthurkrupa** [comment]
I've made a stupid mistake when refactoring. Please check if the patch in 1.2.1 fixes it (I'm won't be able to see for myself during the next couple of days).

**Comment by dragonflyuk** [comment]
I'll give it ago later today, thanks.

**Comment by dragonflyuk** [comment]
No obvious errors in the log, but it's like messages are been sent to the units, but status is not been returned.

**Comment by bboti86** [comment]
Hi, 
I think I have the same issue, running 1.2.1 now. 
My logs show nothing really, only this comes up every once in a while: 
2019-05-02 22:40:20 ERROR (MainThread) [homeassistant.components.mqtt.climate] Could not parse temperature from 
My system was working great before 1.2 came. 
Let us know if we should test something for you! 
B

**Comment by arthurkrupa** [comment]
Ok I've also fixed another stupid bug which blocked the power state from being updated.

Please try running v1.2.2 and let me know how is works.

**Comment by dragonflyuk** [comment]
Just gave it a quick try, looks like it's overloading my hassio server, but did get the warnings

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})

**Comment by dragonflyuk** [comment]
Having slept on it, it looks like my MQTT server crashed curing installation,I can't say wether it was related or not, but I've restarted Mosquito this morning and things are looking better, the main thermostat and mode appears to be working now, however the light, sleep and health setting appear not to be updating. I can see the messages been sent when I try to trigger them, they are not been sent to the units Has something changed with these settings?

0|HVAC_0  | [MQTT] Message "1" received for home/greehvac/health/set
0|HVAC_0  | [UDP] Status updated on 1e482204
0|HVAC_0  | [MQTT] Message "1" received for home/greehvac/health/set
0|HVAC_0  | [UDP] Status updated on 1e482204
0|HVAC_0  | [MQTT] Message "1" received for home/greehvac/lights/set
0|HVAC_0  | [UDP] Status updated on 1e482204
0|HVAC_0  | [MQTT] Message "1" received for home/greehvac/lights/set
0|HVAC_0  | [UDP] Status updated on 1e482204
