### ISSUE TITLE
error in homeassistant.log

### ISSUE THREAD

**Issue by jarzebskim** [arthurkrupa/gree-hvac-mqtt-bridge#41]
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 121, in handle_call_service
    connection.context(msg))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1150, in async_call
    self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1172, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 194, in handle_service
    required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 316, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 337, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 491, in turn_off
    raise NotImplementedError()
NotImplementedError`

my config:

   name: Gree AC

   
    current_temperature_topic: "home/gree/temperature/get"
    temperature_command_topic: "home/gree/temperature/set"
    temperature_state_topic: "home/gree/temperature/get"
    mode_state_topic: "home/gree/mode/get"
    mode_command_topic: "home/gree/mode/set"
    fan_mode_state_topic: "home/gree/fanspeed/get"
    fan_mode_command_topic: "home/gree/fanspeed/set"
    swing_mode_state_topic: "home/gree/swingvert/get"
    swing_mode_command_topic: "home/gree/swingvert/set"
    power_state_topic: "home/gree/power/get"
    power_command_topic: "home/gree/power/set"

    # Keep the following as is
    payload_off: 0
    payload_on: 1
    modes:
      - "off"
      - "auto"
      - "cool"
      - "heat"
      - "dry"
      - "fan_only"
    swing_modes:
      - "default"
      - "full"
      - "fixedTop"
      - "fixedMidTop"
      - "fixedMid"
      - "fixedMidBottom"
      - "fixedBottom"
      - "swingBottom"
      - "swingMidBottom"
      - "swingMid"
      - "swingMidTop"
      - "swingTop"
    fan_modes:
      - "auto"
      - "low"
      - "mediumLow"
      - "medium"
      - "mediumHigh"
      - "high"

latest hassio 0.94.3

addon config

{
  "mqtt": {
    "broker_url": "mqtt://10.240.1.240",
    "username": "xxx",
    "password": "xxx"
  },
  "devices": [
    {
      "hvac_host": "10.240.1.216",
      "mqtt_topic_prefix": "home/gree"
    }
  ]
}

**Comment by jarzebskim** [comment]
also turn_on not working

Thu Jun 13 2019 21:13:55 GMT+0200 (czas środkowoeuropejski letni)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 121, in handle_call_service
    connection.context(msg))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1150, in async_call
    self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1172, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 194, in handle_service
    required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 316, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 337, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 480, in turn_on
    raise NotImplementedError()
NotImplementedError

I can turn on and off from card but not by service call.
